export interface Heading {
  id: string;
  text: string;
  level: 2 | 3;
}

/** Slugify a heading string to match the id generated by the h2/h3 MDX override */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/** Extract H2 and H3 headings from raw MDX/Markdown content */
export function extractHeadings(content: string): Heading[] {
  const headings: Heading[] = [];
  // Match ## and ### headings (not inside code blocks)
  const lines = content.split('\n');
  let inCodeBlock = false;
  for (const line of lines) {
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      continue;
    }
    if (inCodeBlock) continue;
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);
    if (h2) {
      const text = h2[1].replace(/\*\*/g, '').replace(/`/g, '').trim();
      headings.push({ id: slugify(text), text, level: 2 });
    } else if (h3) {
      const text = h3[1].replace(/\*\*/g, '').replace(/`/g, '').trim();
      headings.push({ id: slugify(text), text, level: 3 });
    }
  }
  return headings;
}
